#!/usr/bin/env node

var exec = require('child_process').exec;

var symbols = {
	ok: '\x1B[32m✓\x1B[39m',
	err: '\x1B[31m✖\x1B[39m'
};

var exit = 0;

var precommit = function () {

	exec('make', function (err, stderr, stdout) {
	
		var result = stderr || stdout;

		if (err || result.indexOf('tests complete') < 0) {
			console.log('tests: ' + symbols.err);
			// exist non-zero to abort the commit
			exit = 1;
		} else {
			console.log('tests: ' + symbols.ok);
		}

		process.exit(exit);

	});

}

console.log('Running pre-commit checks.');